language: node_js

node_js:
  - '10'

services:
  - docker

deploy:
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(develop|master)$
